title: MFMP Docencia
description: Un espacio para enseñar, compartir y aprender
lang: es
timezone: America/Santiago

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - LICENSE
  - CHANGELOG.md
