title: MFMP Docencia
description: Un espacio para enseñar, compartir y aprender
lang: es
timezone: America/Santiago
asset_version: 20260723-13

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - LICENSE
  - CHANGELOG.md
